export type TSiteKey =
  | "1337x"
  | "2Dimensions"
  | "7Cups"
  | "9GAG"
  | "APClips"
  | "About.me"
  | "Academia.edu"
  | "AdmireMe.Vip"
  | "Airbit"
  | "Airliners"
  | "All Things Worn"
  | "AllMyLinks"
  | "AniWorld"
  | "Anilist"
  | "Apple Developer"
  | "Apple Discussions"
  | "Aparat"
  | "Archive of Our Own"
  | "Archive.org"
  | "Arduino Forum"
  | "ArtStation"
  | "Asciinema"
  | "Ask Fedora"
  | "Atcoder"
  | "Vjudge"
  | "Audiojungle"
  | "Autofrage"
  | "Avizo"
  | "AWS Skills Profile"
  | "BOOTH"
  | "Bandcamp"
  | "Bazar.cz"
  | "Behance"
  | "Bezuzyteczna"
  | "BiggerPockets"
  | "BioHacking"
  | "BitBucket"
  | "Bitwarden Forum"
  | "Blipfoto"
  | "Blitz Tactics"
  | "Blogger"
  | "Bluesky"
  | "BongaCams"
  | "Bookcrossing"
  | "BoardGameGeek"
  | "BraveCommunity"
  | "BreachSta.rs Forum"
  | "BugCrowd"
  | "BuyMeACoffee"
  | "BuzzFeed"
  | "Cfx.re Forum"
  | "CGTrader"
  | "CNET"
  | "CSSBattle"
  | "CTAN"
  | "Caddy Community"
  | "Car Talk Community"
  | "Carbonmade"
  | "Career.habr"
  | "CashApp"
  | "Championat"
  | "Chaos"
  | "Chatujme.cz"
  | "ChaturBate"
  | "Chess"
  | "Choice Community"
  | "Clapper"
  | "CloudflareCommunity"
  | "Clozemaster"
  | "Clubhouse"
  | "Code Snippet Wiki"
  | "Codeberg"
  | "Codecademy"
  | "Codechef"
  | "Codeforces"
  | "Codepen"
  | "Coders Rank"
  | "Coderwall"
  | "CodeSandbox"
  | "Codewars"
  | "Codolio"
  | "Coinvote"
  | "ColourLovers"
  | "Contently"
  | "Coroflot"
  | "Cplusplus"
  | "Cracked"
  | "Cracked Forum"
  | "Crevado"
  | "Crowdin"
  | "CryptoHack"
  | "Cryptomator Forum"
  | "Cults3D"
  | "CyberDefenders"
  | "DEV Community"
  | "DMOJ"
  | "DailyMotion"
  | "dcinside"
  | "Dealabs"
  | "DeviantArt"
  | "DigitalSpy"
  | "Discogs"
  | "Discord"
  | "Discord.bio"
  | "Discuss.Elastic.co"
  | "Diskusjon.no"
  | "Disqus"
  | "Docker Hub"
  | "Dribbble"
  | "Duolingo"
  | "Eintracht Frankfurt Forum"
  | "Empretienda AR"
  | "Envato Forum"
  | "Erome"
  | "Exposure"
  | "exophase"
  | "EyeEm"
  | "F3.cool"
  | "Fameswap"
  | "Fandom"
  | "Fanpop"
  | "Finanzfrage"
  | "Flickr"
  | "Flightradar24"
  | "Flipboard"
  | "Football"
  | "FortniteTracker"
  | "Forum Ophilia"
  | "Fosstodon"
  | "Framapiaf"
  | "Freelancer"
  | "Freesound"
  | "GNOME VCS"
  | "GaiaOnline"
  | "Gamespot"
  | "GameFAQs"
  | "GeeksforGeeks"
  | "Genius (Artists)"
  | "Genius (Users)"
  | "Gesundheitsfrage"
  | "GetMyUni"
  | "Giant Bomb"
  | "Giphy"
  | "GitBook"
  | "GitHub"
  | "Warframe Market"
  | "GitLab"
  | "Gitea"
  | "Gitee"
  | "GoodReads"
  | "Google Play"
  | "Gradle"
  | "Grailed"
  | "Gravatar"
  | "Gumroad"
  | "Gutefrage"
  | "HackTheBox"
  | "Hackaday"
  | "HackenProof (Hackers)"
  | "HackerEarth"
  | "HackerNews"
  | "HackerOne"
  | "HackerRank"
  | "HackerSploit"
  | "HackMD"
  | "Harvard Scholar"
  | "Hashnode"
  | "Heavy-R"
  | "Hive Blog"
  | "Holopin"
  | "Houzz"
  | "HubPages"
  | "Hubski"
  | "HudsonRock"
  | "Hugging Face"
  | "IFTTT"
  | "Ifunny"
  | "IRC-Galleria"
  | "Icons8 Community"
  | "Image Fap"
  | "ImgUp.cz"
  | "Imgur"
  | "imood"
  | "Instagram"
  | "Instapaper"
  | "Instructables"
  | "Intigriti"
  | "Ionic Forum"
  | "Issuu"
  | "Itch.io"
  | "Itemfix"
  | "Jellyfin Weblate"
  | "Jimdo"
  | "Joplin Forum"
  | "Jupyter Community Forum"
  | "Kaggle"
  | "kaskus"
  | "Keybase"
  | "Kick"
  | "Kik"
  | "Kongregate"
  | "Kvinneguiden"
  | "LOR"
  | "Laracast"
  | "Launchpad"
  | "LeetCode"
  | "LemmyWorld"
  | "LessWrong"
  | "Letterboxd"
  | "LibraryThing"
  | "Lichess"
  | "LinkedIn"
  | "Linktree"
  | "LinuxFR.org"
  | "Listed"
  | "LiveJournal"
  | "Lobsters"
  | "LottieFiles"
  | "LushStories"
  | "MMORPG Forum"
  | "Mamot"
  | "Medium"
  | "Memrise"
  | "Minecraft"
  | "MixCloud"
  | "Monkeytype"
  | "Motherless"
  | "Motorradfrage"
  | "MuseScore"
  | "MyAnimeList"
  | "MyMiniFactory"
  | "Mydramalist"
  | "Myspace"
  | "NICommunityForum"
  | "namuwiki"
  | "NationStates Nation"
  | "NationStates Region"
  | "Naver"
  | "Needrom"
  | "Newgrounds"
  | "Nextcloud Forum"
  | "Nightbot"
  | "Ninja Kiwi"
  | "NintendoLife"
  | "NitroType"
  | "NotABug.org"
  | "Nothing Community"
  | "Nyaa.si"
  | "ObservableHQ"
  | "Open Collective"
  | "OpenGameArt"
  | "OpenStreetMap"
  | "Odysee"
  | "Opensource"
  | "OurDJTalk"
  | "Outgress"
  | "PCGamer"
  | "PSNProfiles.com"
  | "Packagist"
  | "Pastebin"
  | "Patched"
  | "Patreon"
  | "PentesterLab"
  | "HotUKdeals"
  | "Mydealz"
  | "Chollometro"
  | "PepperNL"
  | "PepperPL"
  | "Preisjaeger"
  | "Pepperdeals"
  | "PepperealsUS"
  | "Promodescuentos"
  | "Periscope"
  | "Pinkbike"
  | "pixelfed.social"
  | "PlayStore"
  | "Playstrategy"
  | "Plurk"
  | "PocketStars"
  | "Pokemon Showdown"
  | "Polarsteps"
  | "Polygon"
  | "Polymart"
  | "Pornhub"
  | "ProductHunt"
  | "programming.dev"
  | "Pychess"
  | "PromoDJ"
  | "Pronouns.page"
  | "PyPi"
  | "Python.org Discussions"
  | "Rajce.net"
  | "Rarible"
  | "Rate Your Music"
  | "Rclone Forum"
  | "RedTube"
  | "Redbubble"
  | "Reddit"
  | "Realmeye"
  | "Reisefrage"
  | "Replit.com"
  | "ResearchGate"
  | "ReverbNation"
  | "Roblox"
  | "RocketTube"
  | "RoyalCams"
  | "Ruby Forums"
  | "RubyGems"
  | "Rumble"
  | "RuneScape"
  | "SWAPD"
  | "Sbazar.cz"
  | "Scratch"
  | "Scribd"
  | "SEOForum"
  | "ShitpostBot5000"
  | "Signal"
  | "Sketchfab"
  | "Slack"
  | "Slant"
  | "Slashdot"
  | "SlideShare"
  | "Slides"
  | "SmugMug"
  | "Smule"
  | "Snapchat"
  | "SOOP"
  | "SoundCloud"
  | "SourceForge"
  | "SoylentNews"
  | "SpeakerDeck"
  | "Speedrun.com"
  | "Spells8"
  | "Splice"
  | "Splits.io"
  | "Sporcle"
  | "Sportlerfrage"
  | "SportsRU"
  | "Spotify"
  | "Star Citizen"
  | "Status Cafe"
  | "Steam Community (Group)"
  | "Steam Community (User)"
  | "Strava"
  | "SublimeForum"
  | "TETR.IO"
  | "TheMovieDB"
  | "TikTok"
  | "Tiendanube"
  | "Topcoder"
  | "Topmate"
  | "TRAKTRAIN"
  | "Telegram"
  | "Tellonym.me"
  | "Tenor"
  | "Terraria Forums"
  | "ThemeForest"
  | "tistory"
  | "TnAFlix"
  | "TradingView"
  | "Trakt"
  | "TrashboxRU"
  | "Trawelling"
  | "Trello"
  | "TryHackMe"
  | "Tuna"
  | "Tweakers"
  | "Twitch"
  | "Trovo"
  | "Twitter"
  | "Typeracer"
  | "Ultimate-Guitar"
  | "Unsplash"
  | "Untappd"
  | "Valorant Forums"
  | "VK"
  | "VSCO"
  | "Velog"
  | "Velomania"
  | "Venmo"
  | "Vero"
  | "Vimeo"
  | "VirusTotal"
  | "VLR"
  | "WICG Forum"
  | "Wakatime"
  | "Warrior Forum"
  | "Wattpad"
  | "WebNode"
  | "Weblate"
  | "Weebly"
  | "Wikidot"
  | "Wikipedia"
  | "Windy"
  | "Wix"
  | "WolframalphaForum"
  | "WordPress"
  | "WordPressOrg"
  | "Wordnik"
  | "Wykop"
  | "Xbox Gamertag"
  | "Xvideos"
  | "YandexMusic"
  | "YouNow"
  | "YouPic"
  | "YouPorn"
  | "YouTube"
  | "akniga"
  | "authorSTREAM"
  | "babyblogRU"
  | "chaos.social"
  | "couchsurfing"
  | "d3RU"
  | "dailykos"
  | "datingRU"
  | "devRant"
  | "drive2"
  | "eGPU"
  | "eintracht"
  | "fixya"
  | "fl"
  | "forum_guns"
  | "freecodecamp"
  | "furaffinity"
  | "geocaching"
  | "habr"
  | "hackster"
  | "hunting"
  | "igromania"
  | "interpals"
  | "irecommend"
  | "jbzd.com.pl"
  | "jeuxvideo"
  | "kofi"
  | "kwork"
  | "last.fm"
  | "leasehackr"
  | "livelib"
  | "mastodon.cloud"
  | "mastodon.social"
  | "mastodon.xyz"
  | "mstdn.social"
  | "mercadolivre"
  | "minds"
  | "moikrug"
  | "mstdn.io"
  | "nairaland.com"
  | "n8n Community"
  | "nnRU"
  | "note"
  | "npm"
  | "omg.lol"
  | "opennet"
  | "osu!"
  | "phpRU"
  | "pikabu"
  | "Pinterest"
  | "pr0gramm"
  | "prog.hu"
  | "satsisRU"
  | "sessionize"
  | "social.tchncs.de"
  | "spletnik"
  | "svidbook"
  | "threads"
  | "toster"
  | "tumblr"
  | "uid"
  | "write.as"
  | "xHamster"
  | "znanylekarz.pl"
  | "Platzi"
  | "BabyRu";

interface Headers6 {
  "Sec-Fetch-Mode": string;
}

interface Headers5 {
  Host: string;
}

interface Headers4 {
  "accept-language": string;
}

interface Headers3 {
  Cookie: string;
}

interface Headers2 {
  Accept: string;
}

interface Headers {
  "Content-Type": string;
}

interface Requestpayload2 {
  username: string;
}

interface Requestpayload {
  query: string;
  variables: Variables;
}

interface Variables {
  name: string;
}

export interface TSite {
  __comment__?: string;
  errorMsg?: string[] | string;
  isNSFW?: boolean;
  regexCheck?: string;
  request_payload?: Requestpayload | Requestpayload2;
  Headers?: Headers | Headers2 | Headers3 | Headers4 | Headers5 | Headers6;
  request_method?: string;
  urlProbe?: string;
  errorType: string;
  url: string;
  urlMain: string;
  username_claimed: string;
}

export type TSites = Record<TSiteKey, TSite>;
